# podman kube play web.deployment.yaml
# podman inspect web-pod-web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      restartPolicy: Always
      containers:
      - name: web
        image: nginx:1.25
        ports:
        - name: http
          containerPort: 80
          hostPort: 8080
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - curl -sf http://localhost:80 || kill 1
          successThreshold: 1
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 256Mi
