# podman kube play web.deployment.yaml
# podman inspect web-pod-web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      restartPolicy: Always
      containers:
      - name: web
        image: nginx:1.25
        ports:
        - name: http
          containerPort: 80
          hostPort: 8080
          protocol: TCP
        startupProbe:
          httpGet:
            scheme: HTTP
            port: 80
            path: /
          successThreshold: 1
          failureThreshold: 3
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            scheme: HTTP
            port: 80
            path: /no/such/resources
          successThreshold: 1
          failureThreshold: 3
          initialDelaySeconds: 10
